apiVersion: v1
kind: Deployment
metadata:
  name: nginx-service
  label:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      label:
        app: nginx
    spec:
      containers:
      -- name: nginx
         image: nginx:1.16
         port:
         -  containerPort: 80